import type { TriviaQuestion } from "./types";

export const QUESTIONS: TriviaQuestion[] = [
  { id: "L1-001", level: 1, domain: "dates_venues", question: "Which stadium hosted WrestleMania 25?", answer: "Reliant Stadium", eraTag: "wm25", distractors: ["Georgia Dome", "Sun Life Stadium", "MetLife Stadium"], usedCount: 0 },
  { id: "L1-002", level: 1, domain: "stats_streaks", question: "Who did The Undertaker defeat in the Streak vs. Career match at WrestleMania XXVI?", answer: "Shawn Michaels", eraTag: "streak", distractors: ["Triple H", "Edge", "Batista"], usedCount: 0 },
  { id: "L1-003", level: 1, domain: "catchphrases_attire", question: "Which three-word chant became synonymous with Daniel Bryan?", answer: "YES! YES! YES!", eraTag: "yes", distractors: ["What? What? What?", "Feed Me More", "You Can't See Me"], usedCount: 0 },
  { id: "L1-004", level: 1, domain: "wtf_moments", question: "On what show did CM Punk deliver the Pipebomb promo on June 27, 2011?", answer: "RAW", eraTag: "punk", distractors: ["SmackDown", "NXT", "ECW"], usedCount: 0 },
  { id: "L1-005", level: 1, domain: "guests_cameos", question: "Who was the official host of WrestleMania XXVII?", answer: "The Rock", eraTag: "wm27", distractors: ["Stone Cold Steve Austin", "Hulk Hogan", "John Cena"], usedCount: 0 },
  { id: "L1-006", level: 1, domain: "storylines", question: "Which rivalry was one of the two headline Showcase stories in WWE 2K15?", answer: "John Cena vs. CM Punk", eraTag: "2k15", distractors: ["John Cena vs. The Rock", "Daniel Bryan vs. The Authority", "The Undertaker vs. Brock Lesnar"], usedCount: 0 },

  { id: "L2-001", level: 2, domain: "dates_venues", question: "Which arena hosted SummerSlam from 2009 through 2014?", answer: "Staples Center", eraTag: "summerslam", distractors: ["Barclays Center", "Madison Square Garden", "Allstate Arena"], usedCount: 0 },
  { id: "L2-002", level: 2, domain: "dates_venues", question: "Where did SummerSlam move for its 2015–2018 residency?", answer: "Barclays Center", eraTag: "summerslam", distractors: ["Staples Center", "TD Garden", "Nassau Coliseum"], usedCount: 0 },
  { id: "L2-003", level: 2, domain: "stats_streaks", question: "Who did Kofi Kingston defeat for the Intercontinental Championship at Over the Limit 2010?", answer: "Drew McIntyre", eraTag: "ic", distractors: ["The Miz", "Wade Barrett", "Dolph Ziggler"], usedCount: 0 },
  { id: "L2-004", level: 2, domain: "catchphrases_attire", question: "Complete The Miz's signature line: “Because I'm The Miz…”", answer: "and I'm AWESOME!", eraTag: "miz", distractors: ["and I'm must-see!", "and I'm the best!", "and you know it!"], usedCount: 0 },
  { id: "L2-005", level: 2, domain: "wtf_moments", question: "On what date did The Nexus make its destructive RAW debut?", answer: "June 7, 2010", eraTag: "nexus", distractors: ["June 21, 2010", "July 18, 2010", "May 17, 2010"], usedCount: 0 },
  { id: "L2-006", level: 2, domain: "milestones", question: "How did the anonymous RAW General Manager communicate with the show?", answer: "A podium laptop and chime", eraTag: "rawgm", distractors: ["A red telephone", "A backstage tablet", "A sealed envelope"], usedCount: 0 },

  { id: "L3-001", level: 3, domain: "dates_venues", question: "Which stadium hosted WrestleMania XXVIII?", answer: "Sun Life Stadium", eraTag: "wm28", distractors: ["Reliant Stadium", "Georgia Dome", "AT&T Stadium"], usedCount: 0 },
  { id: "L3-002", level: 3, domain: "stats_streaks", question: "Who executed the ‘Heist of the Century’ cash-in at WrestleMania 31?", answer: "Seth Rollins", eraTag: "wm31", distractors: ["Dean Ambrose", "Dolph Ziggler", "Roman Reigns"], usedCount: 0 },
  { id: "L3-003", level: 3, domain: "catchphrases_attire", question: "What color attire did Seth Rollins wear at SummerSlam 2015?", answer: "White and gold", eraTag: "rollins", distractors: ["Black and red", "Silver and blue", "Purple and gold"], usedCount: 0 },
  { id: "L3-004", level: 3, domain: "wtf_moments", question: "Who ended The Undertaker's WrestleMania streak?", answer: "Brock Lesnar", eraTag: "21-1", distractors: ["Roman Reigns", "Triple H", "Bray Wyatt"], usedCount: 0 },
  { id: "L3-005", level: 3, domain: "milestones", question: "Which venue hosted the first all-women WWE pay-per-view, Evolution?", answer: "Nassau Coliseum", eraTag: "evolution", distractors: ["TD Garden", "Barclays Center", "Full Sail University"], usedCount: 0 },
  { id: "L3-006", level: 3, domain: "storylines", question: "How many core historic matches were in WWE 2K19's Daniel Bryan Showcase?", answer: "11", eraTag: "2k19", distractors: ["8", "10", "14"], usedCount: 0 },

  { id: "L4-001", level: 4, domain: "dates_venues", question: "What official attendance did WWE announce for WrestleMania 32?", answer: "101,763", eraTag: "wm32", distractors: ["78,363", "72,744", "93,173"], usedCount: 0 },
  { id: "L4-002", level: 4, domain: "stats_streaks", question: "How long was Asuka's NXT/WWE undefeated streak?", answer: "523 days", eraTag: "asuka", distractors: ["434 days", "365 days", "600 days"], usedCount: 0 },
  { id: "L4-003", level: 4, domain: "catchphrases_attire", question: "Which film inspired Rey Mysterio's WrestleMania XXVI ring gear?", answer: "Avatar", eraTag: "rey", distractors: ["Predator", "The Dark Knight", "Iron Man"], usedCount: 0 },
  { id: "L4-004", level: 4, domain: "wtf_moments", question: "Who entered at number 30 to trigger the Royal Rumble 2014 crowd revolt?", answer: "Rey Mysterio", eraTag: "rr14", distractors: ["Batista", "Kane", "Sheamus"], usedCount: 0 },
  { id: "L4-005", level: 4, domain: "milestones", question: "Who contested the first women's Hell in a Cell main event in 2016?", answer: "Sasha Banks and Charlotte Flair", eraTag: "hiac", distractors: ["Bayley and Sasha Banks", "Becky Lynch and Charlotte Flair", "Nikki Bella and Paige"], usedCount: 0 },
  { id: "L4-006", level: 4, domain: "storylines", question: "Which secret bonus match can be unlocked in WWE 2K19's Daniel Bryan Showcase?", answer: "Daniel Bryan vs. Brian Danielson", eraTag: "2k19", distractors: ["Daniel Bryan vs. The Miz", "Daniel Bryan vs. Chris Jericho", "Daniel Bryan vs. John Cena"], usedCount: 0 },

  { id: "L5-001", level: 5, domain: "milestones", question: "Which teams contested the WrestleMania 25 pre-show tag title unification match?", answer: "The Colóns vs. The Miz and John Morrison", eraTag: "wm25", distractors: ["The Colóns vs. Legacy", "Cryme Tyme vs. The Miz and John Morrison", "The Hart Dynasty vs. Legacy"], usedCount: 0 },
  { id: "L5-002", level: 5, domain: "stats_streaks", question: "How long was Antonio Cesaro's obscure 2012 title reign noted in the framework?", answer: "54 days", eraTag: "cesaro", distractors: ["43 days", "67 days", "91 days"], usedCount: 0 },
  { id: "L5-003", level: 5, domain: "catchphrases_attire", question: "Whose yellow kickpads did CM Punk borrow for an emergency 2011 house-show gear swap?", answer: "Kofi Kingston", eraTag: "punk", distractors: ["Rey Mysterio", "Sin Cara", "Evan Bourne"], usedCount: 0 },
  { id: "L5-004", level: 5, domain: "wtf_moments", question: "Which 2009 PPV theme is cited as being dubbed over on WWE Network?", answer: "You're Going Down by Sick Puppies", eraTag: "network", distractors: ["Invincible by MGK", "My House by Flo Rida", "Salute by Little Mix"], usedCount: 0 },
  { id: "L5-005", level: 5, domain: "milestones", question: "When was the first NXT match taped at Full Sail University?", answer: "May 17, 2012", eraTag: "nxt", distractors: ["June 20, 2012", "February 23, 2010", "May 17, 2013"], usedCount: 0 },
  { id: "L5-006", level: 5, domain: "storylines", question: "On which show did the 2003 Bryan Danielson vs. John Cena match take place?", answer: "WWE Velocity", eraTag: "velocity", distractors: ["WWE Heat", "WWE NXT", "WWE Superstars"], usedCount: 0 }
];
